"""initial schema

Revision ID: 2f6e9fdb2e0f
Revises: 
Create Date: 2026-09-26 22:32:37.203957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2f6e9fdb2e0f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unit_name'), 'unit', ['name'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('position', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'user', name='userrole'), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_unit_id'), 'user', ['unit_id'], unique=False)
    op.create_table('meeting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scheduled_start', sa.DateTime(), nullable=False),
    sa.Column('scheduled_end', sa.DateTime(), nullable=True),
    sa.Column('actual_start', sa.DateTime(), nullable=True),
    sa.Column('actual_end', sa.DateTime(), nullable=True),
    sa.Column('location_type', sa.Enum('online', 'offline', name='meetinglocationtype'), nullable=False),
    sa.Column('location_place', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('location_city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_formal', sa.Boolean(), nullable=False),
    sa.Column('contact_person', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('inviting_unit', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('categories', sa.JSON(), nullable=True),
    sa.Column('notes', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('scheduled', 'cancelled', name='meetingstatus'), nullable=False),
    sa.Column('organizer_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organizer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_inviting_unit'), 'meeting', ['inviting_unit'], unique=False)
    op.create_index(op.f('ix_meeting_organizer_id'), 'meeting', ['organizer_id'], unique=False)
    op.create_index(op.f('ix_meeting_scheduled_start'), 'meeting', ['scheduled_start'], unique=False)
    op.create_index(op.f('ix_meeting_status'), 'meeting', ['status'], unique=False)
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('meeting_invitation', 'invitation_revoked', 'meeting_updated', 'meeting_cancelled', 'invitation_accepted', 'invitation_declined', 'invitation_cancelled', name='notificationtype'), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('link', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_created_at'), 'notification', ['created_at'], unique=False)
    op.create_index(op.f('ix_notification_is_read'), 'notification', ['is_read'], unique=False)
    op.create_index(op.f('ix_notification_user_id'), 'notification', ['user_id'], unique=False)
    op.create_table('meetingparticipant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('organizer', 'invitee', name='participantrole'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'declined', 'cancelled', name='participantstatus'), nullable=False),
    sa.Column('response_note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('has_takehome_pay', sa.Boolean(), nullable=False),
    sa.Column('takehome_pay_paid', sa.Boolean(), nullable=False),
    sa.Column('invited_at', sa.DateTime(), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'user_id')
    )
    op.create_index(op.f('ix_meetingparticipant_meeting_id'), 'meetingparticipant', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_meetingparticipant_status'), 'meetingparticipant', ['status'], unique=False)
    op.create_index(op.f('ix_meetingparticipant_user_id'), 'meetingparticipant', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meetingparticipant_user_id'), table_name='meetingparticipant')
    op.drop_index(op.f('ix_meetingparticipant_status'), table_name='meetingparticipant')
    op.drop_index(op.f('ix_meetingparticipant_meeting_id'), table_name='meetingparticipant')
    op.drop_table('meetingparticipant')
    op.drop_index(op.f('ix_notification_user_id'), table_name='notification')
    op.drop_index(op.f('ix_notification_is_read'), table_name='notification')
    op.drop_index(op.f('ix_notification_created_at'), table_name='notification')
    op.drop_table('notification')
    op.drop_index(op.f('ix_meeting_status'), table_name='meeting')
    op.drop_index(op.f('ix_meeting_scheduled_start'), table_name='meeting')
    op.drop_index(op.f('ix_meeting_organizer_id'), table_name='meeting')
    op.drop_index(op.f('ix_meeting_inviting_unit'), table_name='meeting')
    op.drop_table('meeting')
    op.drop_index(op.f('ix_user_unit_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_unit_name'), table_name='unit')
    op.drop_table('unit')
    # ### end Alembic commands ###
    # Postgres keeps enum types after their tables are gone; drop them so a
    # downgrade + upgrade round-trip doesn't fail on "type already exists".
    for enum_name in (
        'participantstatus',
        'participantrole',
        'notificationtype',
        'meetingstatus',
        'meetinglocationtype',
        'userrole',
    ):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
